name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Using Node 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x 
    - run: npm install -g eslint
    - run: eslint ./**/*.js
